### ISSUE TITLE
第二章工程化两个小问题

### ISSUE THREAD

**Issue by chinazxy2008** [ssthouse/mini-program-development-code#42]
1、复制时，wxss文件没有复制进去，是不是样式都不再使用wxss，而使用less和sass文件呢
2、文档中说，用IDE直接打开Dist目录，那Src中的文件用记事本打开吗，可否像webstorm一样，在IDE中编辑源代码的同时，同时IDE中预览效果。

请老师指点，谢谢！

**Comment by ssthouse** [comment]
@chinazxy2008 Hi，
> 1、复制时，wxss文件没有复制进去，是不是样式都不再使用wxss，而使用less和sass文件呢

我们选择的css预处理语言是less或sass，在webpack打包时会自动 `编译-> 修改后缀名`, 所以都用less，sass文件即可。

> 2、文档中说，用IDE直接打开Dist目录，那Src中的文件用记事本打开吗，可否像webstorm一样，在IDE中编辑源代码的同时，同时IDE中预览效果。

按照本书中的开发方式，我们是使用的vscode或者webstorm来编辑src目录， 在小程序IDE中查看dist目录效果。
这也是目前主流的小程序开发方式，因为直接用官方的小程序ID进行接开发确实非常不方便，

**Comment by chinazxy2008** [comment]
明白了，谢谢老师百忙中的回复。
